spring.application.name=CashAccountsManagerBackendApplication
spring.profiles.active=dev
spring.config.import=server.properties, internal_db.properties, jpa.properties, logging.properties, documentation.properties, security.properties, jackson.properties