spring.application.name=CashAccountsManagerBackendApplication
spring.profiles.active=dev
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8

management.endpoints.web.base-path=/api/actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=Cash Account Manager
info.app.description=Spring backend application for registering, managing actions from many accounts in different banks
info.app.version=1.0.0

spring.config.import=server.properties, internal_db.properties, jpa.properties, logging.properties, documentation.properties, security.properties, jackson.properties